title: jmaingot.com
description: This is my personal website.
google_analytics: false
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jekyll-mentions

github:
  is_project_page: false
  is_user_page: true
